version: "3.9"

networks:
  service_network:
    driver: bridge

services:
  db:
    image: postgres:15.4
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - service_network

  service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: django_python_service
    command: tail -F anything
    volumes:
      - ./app:/opt/django-python-service/app
      - ./translation:/opt/django-python-service/translation
      - ./tests:/opt/django-python-service/tests
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=m6PELZ0u3RK-Hah6p88eE-_6CymoqcnKz7l4mXtUlBI8MYLyUOCsHwMs2zI6Fu6CD0U
      - ENVIRONMENT=DEV
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - service_network
